"""Nombres legibles para los CSV GEIH 2025 de características generales y ocupados.

Fuente: hoja «Diccionario» del archivo suministrado por el proyecto.
Solo cambia encabezados; los datos y códigos de respuesta permanecen iguales.
Si se unirán módulos mediante sus llaves originales, aplicar después de unir.
"""

# Cada clave es el nombre original de una columna en los CSV suministrados.
NOMBRES_GEIH = {
    "Unnamed: 0": "Indice_Exportacion",
    # Identificación, cobertura y factores de expansión
    "PERIODO": "Periodo_Recoleccion", "MES": "Mes_Encuesta", "PER": "Anio_Encuesta",
    "DIRECTORIO": "Id_Vivienda", "SECUENCIA_P": "Id_Hogar",
    "ORDEN": "Orden_Persona", "HOGAR": "Numero_Hogar", "REGIS": "Tipo_Registro",
    "AREA": "Area_Metropolitana", "CLASE": "Clase_Dominio",
    "FEX_C18": "Factor_Expansion", "DPTO": "Departamento",
    "PT": "Poblacion_Total", "FT": "Fuerza_Trabajo",
    # Características generales
    "P6016": "Orden_Informante", "P3271": "Sexo_Al_Nacer",
    "P6040": "Edad", "P6030S1": "Mes_Nacimiento", "P6030S3": "Anio_Nacimiento",
    "P6050": "Parentesco_Jefe_Hogar", "P6083": "Madre_Reside_Hogar",
    "P6083S1": "Orden_Madre", "P6081": "Padre_Reside_Hogar",
    "P6081S1": "Orden_Padre", "P2057": "Se_Considera_Campesino",
    "P2059": "Fue_Campesino", "P2061": "Comunidad_Campesina",
    "P6080": "Autorreconocimiento_Etnico", "P6080S1": "Pueblo_Indigena",
    "P6080S1A1": "Otro_Pueblo_Indigena", "P6070": "Estado_Conyugal",
    "P6071": "Conyuge_Reside_Hogar", "P6071S1": "Orden_Conyuge",
    "P6090": "Afiliacion_Salud", "P6100": "Regimen_Salud",
    "P6110": "Quien_Paga_Salud", "P6120": "Pago_Mensual_Salud",
    "P1906S1": "Dificultad_Oir", "P1906S2": "Dificultad_Hablar",
    "P1906S3": "Dificultad_Ver", "P1906S4": "Dificultad_Movilidad",
    "P1906S5": "Dificultad_Manipular_Objetos", "P1906S6": "Dificultad_Cognitiva",
    "P1906S7": "Dificultad_Autocuidado", "P1906S8": "Dificultad_Interaccion",
    "P6160": "Sabe_Leer_Escribir", "P6170": "Asiste_Institucion_Educativa",
    "P3041": "Tipo_Institucion_Educativa", "P3042": "Nivel_Educativo",
    "P3042S1": "Grado_Aprobado", "P3042S2": "Area_Nivel_Educativo",
    "P3043": "Titulo_o_Diploma", "P3043S1": "Titulo_Diploma_EnQue",
    "P3038": "Atraccion_Sexual_Romantica", "P3039": "Identidad_Autorreconocida",
    "POB_MAY18": "Poblacion_Mayor_18",
    # Actividad económica, contrato y condiciones del empleo principal
    "P3044S2": "Productos_Comercializados", "P6440": "Tiene_Contrato",
    "P6450": "Contrato_Verbal_Escrito", "P6460": "Plazo_Contrato",
    "P6460S1": "Duracion_Contrato_Meses", "P6400": "Contratante_Es_Lugar_Trabajo",
    "P6410": "Tipo_Empresa_Contratante", "P6422": "Conforme_Tipo_Contrato",
    "P6420S2": "Rama_Empresa_Contratante",
    "P6424S1": "Derecho_Vacaciones_Pagas", "P6424S2": "Derecho_Prima_Navidad",
    "P6424S3": "Derecho_Cesantias", "P6424S5": "Derecho_Licencia_Enfermedad",
    "P6426": "Antiguedad_Trabajo_Meses", "P6430": "Categoria_Trabajo",
    "P6430S1": "Otra_Categoria_Trabajo",
    "P3045S1": "Empresa_Camara_Comercio", "P3045S2": "Empresa_RUT",
    "P3045S3": "Empresa_Personeria_Juridica",
    "P3046": "Empresa_Contabilidad_Contador",
    "P3363": "Medio_Consecucion_Empleo", "P9440": "Empleo_Obtenido_Internet",
    # Salarios, pagos en especie y subsidios
    "P6500": "Salario_Mes_Anterior", "P3364": "Retencion_Salario",
    "P3364S1": "Valor_Retencion_Salario", "P6510": "Recibio_Horas_Extras",
    "P6510S1": "Valor_Horas_Extras", "P6510S2": "Horas_Extras_Incluidas_Salario",
    "P6590": "Recibio_Alimentos_Pago", "P6590S1": "Valor_Alimentos_Pago",
    "P6600": "Recibio_Vivienda_Pago", "P6600S1": "Valor_Vivienda_Pago",
    "P6610": "Usa_Transporte_Empresa", "P6610S1": "Valor_Transporte_Empresa",
    "P6620": "Recibio_Otros_Pagos_Especie", "P6620S1": "Valor_Otros_Pagos_Especie",
    "P6585S1": "Recibio_Subsidio_Alimentacion",
    "P6585S1A1": "Valor_Subsidio_Alimentacion",
    "P6585S1A2": "Subsidio_Alimentacion_Incluido_Salario",
    "P6585S2": "Recibio_Subsidio_Transporte",
    "P6585S2A1": "Valor_Subsidio_Transporte",
    "P6585S2A2": "Subsidio_Transporte_Incluido_Salario",
    "P6585S3": "Recibio_Subsidio_Familiar",
    "P6585S3A1": "Valor_Subsidio_Familiar",
    "P6585S3A2": "Subsidio_Familiar_Incluido_Salario",
    "P6585S4": "Recibio_Subsidio_Educativo",
    "P6585S4A1": "Valor_Subsidio_Educativo",
    "P6585S4A2": "Subsidio_Educativo_Incluido_Salario",
    "P6545": "Recibio_Primas_Mensuales", "P6545S1": "Valor_Primas_Mensuales",
    "P6545S2": "Primas_Incluidas_Salario",
    "P6580": "Recibio_Bonificacion_Mensual",
    "P6580S1": "Valor_Bonificacion_Mensual",
    "P6580S2": "Bonificacion_Incluida_Salario",
    "P6630S1": "Recibio_Prima_Servicios_Anual",
    "P6630S1A1": "Valor_Prima_Servicios_Anual",
    "P6630S2": "Recibio_Prima_Navidad_Anual",
    "P6630S2A1": "Valor_Prima_Navidad_Anual",
    "P6630S3": "Recibio_Prima_Vacaciones_Anual",
    "P6630S3A1": "Valor_Prima_Vacaciones_Anual",
    "P6630S4": "Recibio_Viaticos_Bonificaciones_Anuales",
    "P6630S4A1": "Valor_Viaticos_Bonificaciones_Anuales",
    "P6630S6": "Recibio_Pago_Accidente_Trabajo",
    "P6630S6A1": "Valor_Pago_Accidente_Trabajo",
    "P6640": "Horas_Extras_Semana_Pasada",
    "P6640S1": "Cantidad_Horas_Extras_Semana",
    # Trabajo independiente y negocio propio
    "P1800": "Tiene_Empleados_Ayudantes", "P1800S1": "Cantidad_Empleados_Ayudantes",
    "P1801S1": "Cantidad_Trabajadores_Pagados", "P1801S2": "Cantidad_Socios",
    "P1801S3": "Cantidad_Trabajadores_Sin_Pago",
    "P1802": "Oferta_Productos_Servicios",
    "P3047": "Decide_Horario_Trabajo", "P3048": "Decide_Produccion_Venta",
    "P3049": "Decide_Precios", "P6765": "Forma_Trabajo_Semana_Pasada",
    "P6765S1": "Otra_Forma_Trabajo",
    "P3051": "Honorarios_Profesionales_Mes",
    "P3052": "Ingresos_Comisiones_Mes", "P3053": "Meses_Honorarios_Comisiones",
    "P3365": "Retencion_Independiente",
    "P3365S1": "Valor_Retencion_Independiente",
    "P3054": "Recibio_Alimentos_Pago_Independiente",
    "P3054S1": "Valor_Alimentos_Pago_Independiente",
    "P3055": "Recibio_Vivienda_Pago_Independiente",
    "P3055S1": "Valor_Vivienda_Pago_Independiente",
    "P3056": "Tipo_Actividad_Negocio", "P3057": "Ventas_Mes_Negocio",
    "P6760": "Meses_Ventas_Negocio",
    "P3058S1": "Gasto_Negocio_Salarios_Honorarios_Mes",
    "P3058S2": "Gasto_Negocio_Insumos_Mes",
    "P3058S3": "Gasto_Negocio_Arriendo_Mes",
    "P3058S4": "Gasto_Negocio_Servicios_Mes",
    "P3058S5": "Gasto_Negocio_Transporte_Mes",
    "P3059": "Ventas_Agro_Mineria_12_Meses",
    "P3061": "Meses_Ventas_Agro_Mineria",
    "P3062S1": "Gasto_Agro_Pago_Trabajadores_Anual",
    "P3062S2": "Gasto_Agro_Servicios_Profesionales_Anual",
    "P3062S3": "Gasto_Agro_Transporte_Maquinaria_Anual",
    "P3062S4": "Gasto_Agro_Combustible_Mantenimiento_Anual",
    "P3062S5": "Gasto_Agro_Fertilizantes_Plaguicidas_Anual",
    "P3062S6": "Gasto_Agro_Vacunas_Veterinaria_Anual",
    "P3062S7": "Gasto_Agro_Compra_Animales_Anual",
    "P3062S8": "Gasto_Agro_Alimento_Animales_Anual",
    "P3062S9": "Gasto_Agro_Arriendo_Tierras_Anual",
    "P3063": "Autoconsumo_Produccion_Hogar",
    "P3063S1": "Valor_Autoconsumo_Hogar",
    "P3064": "Propiedad_Tierra_Produccion",
    "P3064S1": "Arriendo_Estimado_Tierra",
    "P3065": "Negocio_Registro_Mercantil",
    "P3066": "Negocio_Contabilidad_Contador",
    "P3067": "Registro_Negocio_Camara_Comercio",
    "P3067S1": "Renovo_Registro_Mercantil",
    "P3067S2": "Anio_Renovacion_Registro",
    "P6775": "Negocio_Lleva_Contabilidad",
    "P3068": "Separa_Gastos_Negocio_Hogar",
    "P6750": "Ganancia_Neta_Negocio_Mes",
    "P3073": "Meses_Ganancia_Neta_Negocio",
    "P550": "Ganancia_Neta_Negocio_12_Meses",
    "P6780": "Tipo_Trabajo_Independiente",
    "P6780S1": "Otro_Trabajo_Independiente",
    "P1879": "Motivo_Trabajo_Independiente",
    "P1805": "Aceptaria_Empleo_Asalariado",
    "P6790": "Meses_Trabajados_12_Meses",
    # Jornada, tamaño del negocio y lugar de trabajo
    "P6800": "Horas_Trabajo_Semanales",
    "P6810": "Motivo_Menos_40_Horas", "P6810S1": "Otro_Motivo_Menos_40_Horas",
    "P6850": "Horas_Trabajo_Semana_Pasada",
    "P6830": "Motivo_Horas_No_Trabajadas",
    "P6830S1": "Otro_Motivo_Horas_No_Trabajadas",
    "P3069": "Personas_Empresa", "P6880": "Lugar_Trabajo",
    "P6880S1": "Otro_Lugar_Trabajo",
    # Seguridad social y trayectoria laboral
    "P6915": "Pago_Enfermedad", "P6915S1": "Otro_Medio_Pago_Enfermedad",
    "P6920": "Cotiza_Pension", "P6930": "Fondo_Pension",
    "P6940": "Quien_Paga_Pension", "P6960": "Anos_Cotizando_Pension",
    "P6990": "Afiliacion_ARL", "P9450": "Afiliacion_Caja_Compensacion",
    "P7020": "Tuvo_Trabajo_Anterior", "P760": "Meses_Sin_Empleo",
    "P7026": "Duracion_Empleo_Anterior", "P7028": "Categoria_Empleo_Anterior",
    "P7028S1": "Otra_Categoria_Empleo_Anterior",
    "P1880": "Motivo_Salida_Empleo_Anterior",
    "P1880S1": "Otro_Motivo_Salida_Empleo",
    # Segundo trabajo y disponibilidad para trabajar más
    "P7040": "Tuvo_Segundo_Trabajo", "P7045": "Horas_Segundo_Trabajo",
    "P3071S3": "Rama_Segundo_Trabajo_P3071S3",
    "P3072S2": "Rama_Segundo_Trabajo_P3072S2",
    "P7050": "Categoria_Segundo_Trabajo",
    "P7070": "Ingreso_Segundo_Trabajo_Mes",
    "P7075": "Personas_Empresa_Segundo_Trabajo",
    "P7077": "Lugar_Segundo_Trabajo",
    "P7090": "Desea_Mas_Horas", "P7100": "Horas_Adicionales_Disponibles",
    "P7110": "Busco_Mas_Horas", "P7120": "Disponible_Mas_Horas",
    # Cambio de empleo y satisfacción
    "P7130": "Desea_Cambiar_Trabajo",
    "P7140S1": "Cambio_Mejorar_Uso_Capacidades",
    "P7140S2": "Cambio_Mejorar_Ingresos",
    "P7140S3": "Cambio_Trabajar_Menos_Horas",
    "P7140S4": "Cambio_Trabajo_Temporal",
    "P7140S5": "Cambio_Problemas_Trabajo",
    "P7140S6": "Cambio_No_Gusta_Trabajo",
    "P7140S7": "Cambio_Esfuerzo_Fisico_Mental",
    "P7140S8": "Cambio_Problemas_Ambientales",
    "P7140S9": "Cambio_Otro_Motivo",
    "P7140S9A1": "Cambio_Cual_Otro_Motivo",
    "P7150": "Busco_Cambiar_Trabajo",
    "P7160": "Disponible_Nuevo_Trabajo_Mes",
    "P7170S1": "Satisfaccion_Trabajo",
    "P7170S5": "Satisfaccion_Prestaciones",
    "P7170S6": "Satisfaccion_Jornada",
    "P7180": "Afiliacion_Gremio_Sindicato",
    "P514": "Trabajo_Estable", "P515": "Compatibilidad_Horario_Familia",
    "P1881": "Medio_Transporte_Trabajo",
    "P1881S1": "Otro_Medio_Transporte",
    "P1882": "Minutos_Desplazamiento_Trabajo",
    "P7240": "Fuente_Recursos_Sin_Trabajo",
    "P7240S1": "Otra_Fuente_Recursos_Sin_Trabajo",
    # Indicadores e industria / oficio
    "OCI": "Indicador_Ocupado", "INGLABO": "Ingreso_Laboral",
    "RAMA2D_R4": "Rama_Act_Empleo_Ppal",
    "RAMA4D_R4": "Rama_Act_Empleo_Ppal_4_Digitos",
    "OFICIO_C8": "Oficio_Clasificado",
}


def renombrar_columnas_geih(df):
    """Devuelve una copia del DataFrame con encabezados legibles y únicos."""
    if not df.columns.is_unique:
        raise ValueError("El DataFrame de entrada contiene nombres de columna repetidos.")
    nombres = [NOMBRES_GEIH.get(col, col) for col in df.columns]
    if len(nombres) != len(set(nombres)):
        raise ValueError("El renombrado crearía columnas repetidas; revisa los encabezados de entrada.")
    return df.rename(columns=NOMBRES_GEIH)
