project: 
  name: "proyecto_final ETL"
  version: "1.0"
  author: "Carlos Andrés Agredo Robles/Juan Andres Gutierrez/ Camilo Ernesto Balanta"

paths:
  bronze_dir: "data/bronze"
  silver_dir: "data/silver"
  gold_dir: "data/gold"
  logs: logs
  # reports_dir: "reports"

source:
  #Usados para extraccion
  caracteristicas_generales_dic: "caracteristicasgenerales_dic.csv"
  ocupados_dic: "ocupados_dic.csv"

  caracteristicas_generales_nov: "caracteristicasgenerales_nov.csv"
  ocupados_nov: "ocupados_nov.csv"

  caracteristicas_generales_oct: "caracteristicasgenerales_oct.csv"
  ocupados_oct: "ocupados_oct.csv"

  #Usados para transformacion
  csv_salida_cg_transformado: "caracteristicasgenerales_transformado.csv"
  csv_salida_ocupados_transformado: "ocupados_trimestre_transformado.csv"
  excel_salida_datasets_traducido_clean: "df_traducido_clean.xlsx"
  #Usados para datos de negocio
  
  excel_salida_gold_data_Cali: "df_gold_data_Cali.xlsx"
  excel_salida_gold_data_KPIs: "df_gold_data_KPIs.xlsx"

  #Usado para logs de ETL
  logs_file: "logs.txt"

  #Usado para previsualizacion
  previsualizacion_KPIs: "previsualizacion_KPIs.xlsx"
